name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      throttr:
        image: ghcr.io/throttr/throttr:2.1.0-release
        ports:
          - 9000:9000

    container:
      image: ghcr.io/throttr/builder-alpine:1.87.0-release

    steps:
      - uses: actions/checkout@v4
      - name: Build and test
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SDK_TESTS=OFF -DBUILD_SDK_BENCHMARK=ON
          make -j4
          
          for i in {1..10}; do
            nc -z throttr 9000 && echo "✅ throttr running ... " && break
            echo "⏳ Try $i: waiting 1s..."
            sleep 1
          done
          
          nc -z throttr 9000 || (echo "❌ throttr isn't running on port 9000" && exit 1)
          
          ./benchmark