name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      throttr:
        image: ghcr.io/throttr/throttr:2.1.0-release
        ports:
          - 9000:9000
        options: >-
          --health-cmd "bash -c 'echo > /dev/tcp/localhost/9000'" 
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

    container:
      image: ghcr.io/throttr/builder-alpine:1.87.0-debug

    steps:
      - uses: actions/checkout@v4
      - name: Build and test
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_SDK_TESTS=ON
          make -j4
          ctest  --output-on-failure --verbose
          cd ..
          gcovr --filter='src/' --print-summary --sort-percentage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}